name: ESG Data Collection

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths: [ 'scripts/**', 'utils/**' ]

jobs:
  collect-esg-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up environment variables
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV
        echo "YAHOO_FINANCE_API_KEY=${{ secrets.YAHOO_FINANCE_API_KEY }}" >> $GITHUB_ENV
        echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV
        echo "ENVIRONMENT=production" >> $GITHUB_ENV
    
    - name: Run data collection
      run: |
        python scripts/data_collector.py
    
    - name: Create summary
      if: always()
      run: |
        echo "## ESG Data Collection Summary" >> $GITHUB_STEP_SUMMARY
        echo "Data collection completed at $(date)" >> $GITHUB_STEP_SUMMARY
        echo "- Environment: ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
        echo "- Python version: $(python --version)" >> $GITHUB_STEP_SUMMARY
    
    - name: Log failure
      if: failure()
      run: |
        echo "❌ ESG Data Collection failed! Check the logs above for details."
        echo "You can manually trigger this workflow from the Actions tab to retry." 